name: lint

on: [push]


jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ github.head_ref }}

      - name: Yarn Install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install 

      - name: Lint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint:check 